version: '3.2'

services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - ./docker/db/dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword1234
      POSTGRES_DB: sfa_development

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
      - "TZ=Asia/Tokyo"
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=mysecretpassword1234"
    links:
      - db
    volumes:
      - ".:/my_app" #共有フォルダの設定
